version: 0.0.{build}.{branch}
skip_tags: true
pull_requests:
  do_not_increment_build_number: true
clone_depth: 10
environment:
    TERM: dumb
    matrix:
      - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
install:
  - gradlew.bat --version
build_script:
  - gradlew.bat -u -i clean assemble
test_script:
  - gradlew.bat -u -i -S check
cache:
  - .gradle
  - C:\Users\appveyor\.gradle
